services:
  mysql:
    image: mysql:latest
    container_name: mysql_prod
    environment:
      MYSQL_ROOT_PASSWORD: P4ssWord
      MYSQL_USER: rocco
      MYSQL_DATABASE: docker4dummies
    #importer
    #volumes:
    # - ./chemin/dump:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma_prod
    links:
      - mysql
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80
    